version: '3'

tasks:
  default:
    cmds:
      - task --list-all

  build:
    desc: Build the Go application
    cmds:
      - go build main.go {{ if .data_dir }}--data_dir={{ .data_dir }}{{ end }}
    generates:
      - main.exe

  execute:
    desc: Execute the compiled Go application on Windows
    cmds:
      - main.exe
    aliases:
      - main

  build-and-execute:
    desc: Build and then execute the Go application
    cmds:
      - task build {{ .data_dir }}
      - task execute
    aliases:
      - be

  run:
    desc: Run the Go application
    cmds:
      - go run main.go {{ if .data_dir }}--data_dir={{ .data_dir }}{{ end }}

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...
